replicaCount: 2

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  DJANGO_DEBUG: "0"
  DJANGO_ALLOWED_HOSTS: "*"
  POSTGRES_DB: "appdb"
  POSTGRES_USER: "dbadmin"
  POSTGRES_PORT: "5432"

externalSecretName: "django-app-secrets"
