controller:
  admin:
    username: "${admin_user}"
    password: "${admin_password}"

  serviceType: ClusterIP

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "2Gi"

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - job-dsl

  JCasC:
    defaultConfig: true
    configScripts:
      seed-job: |
        jobs:
          - script: >
              pipelineJob('django-app-ci') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote { url('${job_repo_url}') }
                        branches('${job_repo_branch}')
                      }
                    }
                    scriptPath('${jenkinsfile_path}')
                  }
                }
              }

agent:
  enabled: true
  namespace: "${namespace}"
  serviceAccount: "${agent_service_account}"

serviceAccountAgent:
  create: false
  name: "${agent_service_account}"

rbac:
  create: true
  readSecrets: true

persistence:
  enabled: true
  storageClass: "gp3"
  size: "8Gi"
