grafana:
  enabled: true
  fullnameOverride: grafana
  adminPassword: "${grafana_password}"
  service:
    type: ClusterIP
    port: 80
  persistence:
    enabled: true
    storageClassName: ${storage_class}
    size: ${grafana_size}
  defaultDashboardsEnabled: true

prometheus:
  prometheusSpec:
    retention: ${prometheus_retain}
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 1Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ${storage_class}
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: ${prometheus_size}

alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

nodeExporter:
  enabled: true
kubeStateMetrics:
  enabled: true

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
